import type { Metadata } from "next";
import { Rubik } from 'next/font/google'
import "./globals.css";

const rubik = Rubik({
  subsets: ['latin'],
  variable: '--font-rubik',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubik.variable} antialiased max-h-screen max-w-[90rem] box-border m-0 p-0`}
      >
        {children}
      </body>
    </html>
  );
}
